package by.perevertkin.solr.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 26 10:15:02 MSK 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArticlesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ArticlesViewImpl() {
    }

    /**
     * Returns the variable value for contentVar.
     * @return variable value for contentVar
     */
    public String getcontentVar() {
        return (String) ensureVariableManager().getVariableValue("contentVar");
    }

    /**
     * Sets <code>value</code> for variable contentVar.
     * @param value value to bind as contentVar
     */
    public void setcontentVar(String value) {
        ensureVariableManager().setVariableValue("contentVar", value);
    }
}

