package by.perevertkin.solr.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 26 14:26:32 MSK 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    ApplicationModule getAm();
}

